//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int KullanıcıID { get; set; }
        public string Adı { get; set; }
        public string Soyadı { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public string Yas { get; set; }
    }
}
